### ISSUE TITLE
Overload with different numbers of arguments

### ISSUE THREAD

**Issue by alancao-uber** [projectnessie/cel-java#110]
[org.projectnessie.cel.interpreter.functions.Overload](https://github.com/projectnessie/cel-java/blob/main/core/src/main/java/org/projectnessie/cel/interpreter/functions/Overload.java) can be created with one of `UnaryOp`, `BinaryOp`, or `FunctionOp`.

In many cases, one overload may have different formats of arguments list. E.g. Strings extension functions from [cel-go](https://github.com/google/cel-go/blob/master/ext/strings.go#L58)
```
//     <string>.indexOf(<string>) -> <int>
//     <string>.indexOf(<string>, <int>) -> <int>
```

It could be possible to create every overload function with `FunctionOp` which accepts variadic arguments. But that will be inconvenient.
The equivalent type in cel-go `function.Overload` is an exported struct. So that developers can create one overload with any of UnaryOp, BinaryOp, and FunctionOp.

Will it help to make the Override [constructor](https://github.com/projectnessie/cel-java/blob/main/core/src/main/java/org/projectnessie/cel/interpreter/functions/Overload.java#L121) public? Or provide another static factory function including all parameters
```
  private Overload(
      String operator, Trait operandTrait, UnaryOp unary, BinaryOp binary, FunctionOp function) {
```

**Comment by snazy** [comment]
Not so happy with making the constructor public, but adding a new factory method in `Overload` that takes e.g. a `BinaryOp` + a `FunctionOp` is fine.
