### ISSUE TITLE
When putting the dependencies in the build.gradle folder, and installing those, it doesn't reflect in any of the files, am I missing something here?

### ISSUE THREAD

**Issue by AarshShah33** [projectnessie/cel-java#138]
The command where you put the implementation files in the build.gradle and use it to install the dependencies, after that the libraries are not being reflected in the folder structure.

**Comment by snazy** [comment]
@AarshShah33 what's the error here? Can you put together a reproducer with current and describe the expected in more details?

**Comment by AarshShah33** [comment]
I am creating a gradle project in which I want to use the cel-java library, as mentioned in the official docs, for a gradle project, you need to add the lines 
    implementation(enforcedPlatform("org.projectnessie.cel:cel-bom:0.3.0"))
    implementation("org.projectnessie.cel:cel-tools")

in your build.gradle
After that, I run the command which builds the file and installs the dependencies, but it doesn't show when I use the import statement.

**Comment by snazy** [comment]
Sorry, I still don't understand what the issue is. Can you please provide a reproducer?

**Comment by AarshShah33** [comment]
This is the build.gradle file 
`plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.6.10'
    id 'java'
    id "application"
    id "io.freefair.lombok" version "6.3.0"
    id "org.jmailen.kotlinter" version "3.7.0"
    id "org.jetbrains.kotlin.plugin.lombok" version "1.6.10"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.8.1"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.8.1"
    implementation "com.github.jkcclemens:khttp:-SNAPSHOT"
    implementation 'io.kubernetes:client-java:14.0.1'
    implementation(enforcedPlatform("org.projectnessie.cel:cel-bom:0.3.0"))
    implementation("org.projectnessie.cel:cel-tools")


}

test {
    useJUnitPlatform()
}
`
And after running this, the libraries for the project should be available inside the project right? But the libraries 
import org.projectnessie.cel.checker.Decls;
import org.projectnessie.cel.tools.Script;
import org.projectnessie.cel.tools.ScriptHost;
are not reflecting in the same project i.e there is some issues with the dependency installation

**Comment by snazy** [comment]
Can you provide a full reproducer and maybe look in parallel what could be causing this?

**Comment by AarshShah33** [comment]
How to provide a reproducer?

**Comment by snazy** [comment]
Just setup a self contained Gradle project and attach it to this issue as a tar or zip

**Comment by AarshShah33** [comment]
[javacel.zip](https://github.com/projectnessie/cel-java/files/8415182/javacel.zip)

**Comment by AarshShah33** [comment]
<img width="1792" alt="Screenshot 2022-04-05 at 11 14 36 AM" src="https://user-images.githubusercontent.com/99003233/161686756-e7ff077c-b1e7-44fc-a8f9-ff57fde4718e.png">

**Comment by AarshShah33** [comment]
did u get what's the issue?

**Comment by AarshShah33** [comment]
So what changes do I need to make in the repo?

**Comment by snazy** [comment]
Use 0.3.2
