### ISSUE TITLE
Accept variable resolution function instead of map from Script.execute

### ISSUE THREAD

**Issue by msbarry** [projectnessie/cel-java#250]
Hello, first of all thanks for building this project! I'm considering using it for adding dynamic expression support to planetiler yaml config files (https://github.com/onthegomap/planetiler/issues/179). For this I need to construct hierarchical contexts where each nested one adds some global variables beyond what the parent context has.

It looks like the `Activation` utility describes what I'm trying to do, but the `Script#execute` function only takes a `Map`.  Would it make sense for another variation on that to take an `Activation` or even just a `Function<String, Object>` ? I'm happy to make a PR to add this, just want to check if this is the right approach first? Or if there's another way of doing this that I'm missing?

**Comment by snazy** [comment]
Hi @msbarry , yup, your proposal to have something in `Script` that helps utilizing `Activation` (without a parent activation, so a `Function`-ish thingy) makes sense. If you can post a PR, that would be really great!

**Comment by msbarry** [comment]
Thanks @snazy, I just opened #251. Let me know what you think.
