### ISSUE TITLE
Handling nulls in the root fields of the JSON object

### ISSUE THREAD

**Issue by stashkevi4** [projectnessie/cel-java#360]
Hey team!

I need ability to check `nulls` in the root fields of the JSON object.

Example:
```java
package evaluator;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;
import org.projectnessie.cel.checker.Decls;
import org.projectnessie.cel.tools.Script;
import org.projectnessie.cel.tools.ScriptHost;

import java.util.Map;

import static junit.framework.TestCase.assertTrue;

public class JavaCelEvaluator {

  @Test
  public void testRootForNull() throws Exception {
    var celExpression = "foo == null";
    var payloadJson = "{\"foo\":null}";

    var mapper = new ObjectMapper();
    JsonNode jsonNode = mapper.readTree(payloadJson);
    var payloadMap = mapper.convertValue(jsonNode, new TypeReference<Map<String, Object>>() { });

    var scriptHost = ScriptHost.newBuilder().build();
    Script script = scriptHost.buildScript(celExpression)
        .withDeclarations(Decls.newVar("foo", Decls.Any))
        .build();

    var result = script.execute(Boolean.class, payloadMap);

    assertTrue(result);
  }
}
```

This UnitTest is throwing exception:

```
undeclared reference to 'id: 1, attributes: [id: 1, names: [foo]]' (in container '')
org.projectnessie.cel.tools.ScriptExecutionException: 
	at org.projectnessie.cel.tools.Script.evaluate(Script.java:59)
	at org.projectnessie.cel.tools.Script.execute(Script.java:45)
	at com.auvik.platform.alerting.condition.evaluator.JavaCelEvaluator.testRootForNull(JavaCelEvaluator.java:31)
```

The problem is appearing only for root fields, i.e. the same test with this values works great:

```java
var celExpression = "foo.bar == null";
var payloadJson = "{\"foo\":{\"bar\":null}}";
```

The cause of this exception is in the following `null` checks [here](https://github.com/projectnessie/cel-java/blob/fcecfe222d23396bbf8c2362764ed94847f22a15/core/src/main/java/org/projectnessie/cel/interpreter/AttributeFactory.java#L614) and [here](https://github.com/projectnessie/cel-java/blob/fcecfe222d23396bbf8c2362764ed94847f22a15/core/src/main/java/org/projectnessie/cel/interpreter/Interpretable.java#L1699).

Is it possible to delete those checks? 

If not, how can I check root fields for `null` without changing CEL expression?

P.S. the same unit test with [cel-go](https://github.com/google/cel-go) works fine.

**Comment by snazy** [comment]
> Is it possible to delete those checks?

I doubt. That's how CEL behaves (wrt to the CEL conformance tests).

> P.S. the same unit test with [cel-go](https://github.com/google/cel-go) works fine.

That's surprising, because those pieces of code actually come from CEL-Go.

Do you wanna take a stab on this issue then?
