### ISSUE TITLE
Dynamic typing with list types

### ISSUE THREAD

**Issue by buildbreaker** [projectnessie/cel-java#412]
Hello,

I'm trying to use CEL to determine if a string is in a dynamic list type. Here's the snippet of code that i'm using to determine if the argument "this" which is of string value "nothello" to be validated with the "rules" where the valid string values are "hello" and "world".
```java
@Test
public void myScriptUsage() throws ScriptException {
    ScriptHost scriptHost = ScriptHost.newBuilder().build();
    Script script = scriptHost.buildScript("!(this in dyn(rules)['in']) ? 'value must be in list' : ''")
            .withDeclarations(
                    // Variable declarations - we need `this` and `rules` in this example
                    Decls.newVar("this", Decls.String),
                    Decls.newVar("rules", Decls.newListType(Decls.String)))
            .build();

    Map<String, Object> arguments = new HashMap<>();
    arguments.put("this", "nothello");
    arguments.put("rules", new String[]{"hello", "world"});

    String result = script.execute(String.class, arguments);

    System.out.println(result);
}
```

When I try to use this I see the following error:
```
message: unsupported index type 'string' in list
org.projectnessie.cel.tools.ScriptExecutionException: message: unsupported index type 'string' in list
```

I did a bit of digging with my colleague and found that the underlying list types are accessed via [index in a list](https://github.com/projectnessie/cel-java/blob/efc930ada1e5077ebc60798c7092fa606e0b3b33/core/src/main/java/org/projectnessie/cel/common/types/ListT.java#L306).

How do you feel about supporting a use case like this?

**Comment by snazy** [comment]
Since lists (`ListT`) support `Container.contains(Val)`, this sounds legit to me.
Looks like `AttributeFactory.refResolve` needs to be made aware of `Container` in a way that doesn't conflict with `Indexer.get(Val)`.
Mind providing a PR?

**Comment by buildbreaker** [comment]
@snazy I have been working on a change that I can put up and we can collaborate more concretely on. Let me get that up and you can communicate where all the pieces should go.

Thank you for your quick responses @snazy !

**Comment by buildbreaker** [comment]
@snazy I was able to get a test passing here: https://github.com/projectnessie/cel-java/pull/413

**Comment by buildbreaker** [comment]
Closed in favor of: https://github.com/projectnessie/cel-java/pull/417

That was the actual root cause.
