### ISSUE TITLE
Residual AST causing "no such overload: int.@in(double,int,...)"

### ISSUE THREAD

**Issue by buildbreaker** [projectnessie/cel-java#423]
`Env.residualAst` contains some unexpected behavior related to double values:

- Due to the usage of `astToString` there are potentially lossy translations with doubles
- Within `astToString` it calls `Unparser.visit` which eventually calls down to `Debug.formatLiteral` which has special handling for [[whole double values](https://github.com/projectnessie/cel-java/blob/main/core/src/main/java/org/projectnessie/cel/common/debug/Debug.java#L87-L91)](https://github.com/projectnessie/cel-java/blob/main/core/src/main/java/org/projectnessie/cel/common/debug/Debug.java#L87-L91).

This test will exercise this path:

```java
@Test
public void doubleInList() {
  Env env = Env.newEnv();
  Env.AstIssuesTuple compile = env.compile("1.0 in [123.5, 123.0]");
  if (compile.getIssues().err() != null) {
    throw compile.getIssues().err();
  }
  Program program = env.program(compile.getAst());
  Program.EvalResult evalResult = program.eval(Activation.emptyActivation());
  // residualAst() is what triggers this lossy translation.
  Ast ast = env.residualAst(compile.getAst(), evalResult.getEvalDetails());
	Program.EvalResult eval = finalProgram.eval(Activation.emptyActivation());
  assertThat(eval.getVal().value().toString()).isEqualTo("false");;
}
```

```java
 expected: "false"
 but was: "no such overload: int.@in(double,int,...)"
org.opentest4j.AssertionFailedError: 
expected: "false"
 but was: "no such overload: int.@in(double,int,...)"
	at java.base@17.0.4/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.4/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.4/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at app//org.projectnessie.cel.ListContainsTest.doubleInList(ListContainsTest.java:172)
	...
```

I’m not sure what the actual fix is here but I know that if I exclude the special handling in `Debug.formatLiteral` it causes some tests to fail in `CheckerTest.java` due to hard coded values

**Comment by snazy** [comment]
Interesting.
The code in `Debug` was basically copied (to provide the same semantics) from CEL-Go's `debug.go`, which strips the trailing '.0`.
I'm okay with changing it, because it's "debug".

**Comment by buildbreaker** [comment]
@snazy If it helps any, the CEL-Go folks ended up making a similar fix here: https://github.com/google/cel-go/pull/686/files
