### ISSUE TITLE
Arbitrary json input

### ISSUE THREAD

**Issue by lightyear0903** [projectnessie/cel-java#517]
Hi Team,

would it be possible to use arbitrary json as input when evaluating, I have an use case for which I can't predefine any jackson pojo class as type to represent the json value in advance. 

Thanks VM in advance for the help.

**Comment by dimas-b** [comment]
Would converting it to a `Map` work?

**Comment by snazy** [comment]
Have you tried to parse the JSON via Jackson as a `JsonNode`?

**Comment by snazy** [comment]
BTW: https://project-nessie.zulipchat.com/ is our public chat. There's a stream `cel-java` for questions.

**Comment by jian-tang-tangram** [comment]
> Would converting it to a `Map` work?

Thanks a lot @dimas-b , the json input might be any valid json, it could be a string or number or json object. For the case of a map, what declaration var type should I use? Really appreciate if you could point me to an example.

**Comment by lightyear0903** [comment]
> Would converting it to a `Map` work?

Thanks a lot @dimas-b . the json could be any valid json value, it could be a string or a json object. For the case of json object, I am wondering what declaration var type should I use.

**Comment by lightyear0903** [comment]
@snazy , thanks VM! For `JsonNode`, I am wondering what should I use as type when declaring the var for the script. I will ask the same question in the public chat, thanks again

**Comment by lightyear0903** [comment]
Issue can be closed. Using proto struct / value can represent Json value
