### ISSUE TITLE
README example doesn't work with protobuf

### ISSUE THREAD

**Issue by sufiand** [projectnessie/cel-java#84]
I tried following the example listed in README for Protobuf and even for a simple POJO. But it doesn't work. And fails with the error:

`Exception in thread "main" org.projectnessie.cel.tools.ScriptCreateException: check failed: ERROR: <input>:1:4: [internal] unexpected failed resolution of 'com.example.helloworld.MyPojo'
 | inp.Property1 == checkName`

Here is the code: 
`  ScriptHost scriptHost = ScriptHost.newBuilder().build();

        Script script = scriptHost.buildScript("inp.Property1 == checkName")
            .withDeclarations(
                Decls.newVar("inp", Decls.newObjectType(MyPojo.class.getName())),
                Decls.newVar("checkName", Decls.String))
            .build();

        MyPojo pojo = new MyPojo();
        pojo.Property1 = "test";

        String checkName = "test";

        Map<String, Object> arguments = new HashMap<>();
        arguments.put("inp", pojo);
        arguments.put("checkName", checkName);

        Boolean result = script.execute(Boolean.class, arguments);`

On a side note, are there any examples in Java that we can leverage?

**Comment by snazy** [comment]
It's a bit difficult to know what's going on without seeing the .proto or the actual MyPojo class. I suspect, either you have to use a lower case property name or use a `.withContainer()` on the builder which corresponds to `org.projectnessie.cel.EnvOption#container`.

There are a bunch of conformance tests from the Google cel-spec repo (in `submodules/cel-spec/`) and maybe `CELTest` and `InterpreterTest`. But we don't have a set of examples or tutorials.

**Comment by snazy** [comment]
Another note: for protobuf, CEL-Java works the same as CEL-Go. The `ScriptHost` is just a convenience thing around the `TypeRegistry`, `Env`, `Ast`, `Program` stuff.

**Comment by buildbreaker** [comment]
I am giving your example a go with the following protobuf and I'm running into a similar problem. Here's the protobuf that I'm using:
```
syntax = "proto3";

message MyPojo {
  string Property1 = 1;
}
```

The code is identical to what @sufiand has. @snazy do you happen to know how to get something like this working? I would like to help out with updating the docs if I'm able to get this working!

**Comment by snazy** [comment]
The Jackson example in the README is fine though. Note that you have to configure the `ScriptHost` with `.registry(JacksonRegistry.newRegistry())` - otherwise plain Java objects won't work (because Jackson's not used then).

**Comment by snazy** [comment]
Protobuf:

```java
public class MyClass {
  public Boolean evalWIthProtobuf() {
    ScriptHost scriptHost = ScriptHost.newBuilder().build();

    Script script =
        scriptHost
            .buildScript("inp.Property1 == checkName")
            .withDeclarations(
                // protobuf types need the type's full name
                Decls.newVar("inp", Decls.newObjectType(Dummy.MyPojo.getDescriptor().getFullName())),
                Decls.newVar("checkName", Decls.String))
            // protobuf types need the default instance
            .withTypes(Dummy.MyPojo.getDefaultInstance())
            .build();

    Dummy.MyPojo pojo = Dummy.MyPojo.newBuilder().setProperty1("test").build();

    String checkName = "test";

    Map<String, Object> arguments = new HashMap<>();
    arguments.put("inp", pojo);
    arguments.put("checkName", checkName);

    Boolean result = script.execute(Boolean.class, arguments);

    return result;
  }
}
```


Jackson:
```java
import org.projectnessie.cel.types.jackson.JacksonRegistry;

public class MyClass {
  public Boolean evalWithJacksonObject(MyInput input, String checkName) {
    // Build the script factory
    ScriptHost scriptHost = ScriptHost.newBuilder()
        // IMPORTANT: use the Jackson registry
        .registry(JacksonRegistry.newRegistry())
        .build();

    // Create the script, will be parsed and checked.
    // It checks whether the property `name` in the "Jackson-ized" class `MyInput` is
    // equal to the value of `checkName`.
    Script script = scriptHost.buildScript("inp.name == checkName")
        // Variable declarations - we need `inp` +  `checkName` in this example
        .withDeclarations(
            // types for Jackson need the fully qualified class name 
            Decls.newVar("inp", Decls.newObjectType(MyInput.class.getName())),
            Decls.newVar("checkName", Decls.String))
        // Register our Jackson object input type (as a java.lang.Class)
        .withTypes(MyInput.class)
        .build();

    Map<String, Object> arguments = new HashMap<>();
    arguments.put("inp", input);
    arguments.put("checkName", checkName);

    Boolean result = script.execute(Boolean.class, arguments);

    return result;
  }
}
```

**Comment by snazy** [comment]
#403 should clarify that

**Comment by buildbreaker** [comment]
Hey @snazy, thanks for your quick response! I'm going to give it a shot later today!

**Comment by buildbreaker** [comment]
@snazy It worked! This was the line that I was missing:
```            
.withTypes(Dummy.MyPojo.getDefaultInstance())
```
